import numpy as np 
import os


"""
NUMPY ADALAH LIBRARY DARI PYTHON YANG BERFUNGSI UNTUK MEMBANTU PROSES PERHITUNGAN DATA
"""
os.system("clear")

# ARRAY DENGAN MENGUNAKAN FUNGSI DARI NUMPY, SEPERTI DIBAWAH INI : 

# 1. DATA ARRAY SATU DIIMENSI

angka = [1,2,3,4,5]
angkaNp = np.array(angka) # MENGGUNAKAN FUNGSI ATAU METHOD ARRAY
print(angkaNp)


# 2. DATA ARRAY DUA DIMENSI, BARIS DAN KOLOM 

angka2 = [[1,2,3],[4,5,6],[7,8,9]]
angkaNp2 = np.array(angka2) 
print(angkaNp2)

# 3. DATA ARRAY DENGAN RENTANG NILAI TERTENTU

angka3 = np.arange(0,10) # MEMILIKI DATA DENGAN RENTANG NILAI 0 - 9 
print(angka3)

angka4 = np.arange(0,9,2) # MEMILIKI DATA DENGAN RENTANG NILAI 0 - 9 DAN MEMILIKI JARAK 2
print(angka4)


# 3. DATA ARRAY DENGAN NILAI TERTENTU

angka5 = np.zeros(4) # FUNGSI UNTUK MENGISI DATA DENGAN NILAI 0
print(angka5)

angka6 = np.zeros((2,4)) # FUNGSI UNTUK MENGISI DATA 0 DEENGAN MODEL 2 DIMENSI
print(angka6)

angka7 = np.ones(4) # FUNGSI UNTUK MENGISI DATA DENGAN NILAI 1
print(angka7)

angka8 = np.ones((2,4)) # FUNGSI UNTUK MENGISI DATA 1 DEENGAN MODEL 2 DIMENSI
print(angka8)

# 4. SATU SET ANGKA DENGAN SPASI MERATA DALAM INTERVAL YANG DITENTUKAN

angka9 = np.linspace(0,8,10)
print(angka9)

# 5. IDENTITY MATRIX = UNTUK MENGHASILKAN MATRIKS IDENTITAS DENGAN DIMENSI YANG DITETAPKAN
angka10 = np.eye(3)
print(angka10)